-- TakeOff backend schema + security policies

create extension if not exists pgcrypto;

create table if not exists public.users (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  full_name text,
  is_premium boolean not null default false,
  premium_activated_at timestamptz,
  payment_reference text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.schools (
  id bigint generated by default as identity primary key,
  name text not null,
  location text not null,
  country text not null,
  fleet_size integer,
  estimated_cost_inr integer,
  duration_months integer,
  hidden_fees text,
  contact text,
  email text,
  website text,
  rating numeric(2,1),
  reviews_count integer default 0,
  multi_engine_available boolean not null default false,
  is_featured boolean not null default false,
  last_verified_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.study_material (
  id bigint generated by default as identity primary key,
  subject text not null,
  title text not null,
  category text,
  description text,
  file_url text,
  premium boolean not null default false,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.medical_centers (
  id bigint generated by default as identity primary key,
  name text not null,
  location text not null,
  center_type text not null,
  address text,
  contact text,
  email text,
  website text,
  appointment_link text,
  is_premium boolean not null default false,
  last_verified_at timestamptz,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.payments (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  provider text not null default 'razorpay',
  order_id text not null unique,
  payment_id text unique,
  signature text,
  status text not null,
  amount integer not null,
  currency text not null default 'INR',
  metadata jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists schools_location_idx on public.schools(location);
create index if not exists schools_country_idx on public.schools(country);
create index if not exists schools_cost_idx on public.schools(estimated_cost_inr);
create index if not exists schools_multi_engine_idx on public.schools(multi_engine_available);
create index if not exists study_material_subject_idx on public.study_material(subject);
create index if not exists study_material_premium_idx on public.study_material(premium);
create index if not exists medical_centers_location_idx on public.medical_centers(location);
create index if not exists payments_user_id_idx on public.payments(user_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists users_set_updated_at on public.users;
create trigger users_set_updated_at
before update on public.users
for each row execute function public.set_updated_at();

drop trigger if exists schools_set_updated_at on public.schools;
create trigger schools_set_updated_at
before update on public.schools
for each row execute function public.set_updated_at();

drop trigger if exists payments_set_updated_at on public.payments;
create trigger payments_set_updated_at
before update on public.payments
for each row execute function public.set_updated_at();

alter table public.users enable row level security;
alter table public.schools enable row level security;
alter table public.study_material enable row level security;
alter table public.medical_centers enable row level security;
alter table public.payments enable row level security;

create policy "users_can_view_own_profile"
  on public.users for select
  to authenticated
  using (auth.uid() = id);

create policy "users_can_insert_own_profile"
  on public.users for insert
  to authenticated
  with check (auth.uid() = id);

create policy "users_can_update_own_profile"
  on public.users for update
  to authenticated
  using (auth.uid() = id)
  with check (auth.uid() = id);

create policy "schools_are_readable_to_authenticated"
  on public.schools for select
  to authenticated
  using (true);

create policy "study_material_free_or_premium"
  on public.study_material for select
  to authenticated
  using (
    premium = false
    or exists (
      select 1
      from public.users u
      where u.id = auth.uid()
        and u.is_premium = true
    )
  );

create policy "medical_centers_free_or_premium"
  on public.medical_centers for select
  to authenticated
  using (
    is_premium = false
    or exists (
      select 1
      from public.users u
      where u.id = auth.uid()
        and u.is_premium = true
    )
  );

create policy "payments_visible_to_owner"
  on public.payments for select
  to authenticated
  using (user_id = auth.uid());

-- service role should own payment writes; block client writes.
revoke insert, update, delete on public.payments from authenticated, anon;
